### ISSUE TITLE
Issue with Youtube video with id containing underscore

### ISSUE THREAD

**Issue by habibrosyad** [yh-luo/webviewtube#6]
Hi,

I found out that this package cannot work properly when loading Youtube video with id containing underscore (e.g. `i_ZrWS8wMMI`), other than that it works just fine.

From some experiments loading the IFrame API in webview, I found out that it is might be because of the webview_flutter. In flutter_inappwebview there is no such issue happening.

**Comment by yh-luo** [comment]
Hi,
Thanks for the report. I think the problem lies in iframe API but not `webview_flutter` or this package.
The same problem happens even for the embedded code provided by YouTube. Using any browsers to open the following html shows the same problem.

It's strange that `flutter_inappwebview` does not suffer from this problem. Could you provide the code that works on `flutter_inappweview`? It would be helpful.

**Embedded code**
```html
<iframe width="1440" height="672" src="https://www.youtube.com/embed/i_ZrWS8wMMI" title="" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
```

**Comment by yh-luo** [comment]
Hi,
I was unable to reproduce the problem on other videos (e.g, `RA-vLF_vnng`, `l6hw4o6_Wcs`). It seems to me that the problem only occurs to this specific video `i_ZrWS8wMMI`. Closed unless more information is available.
